resources:
  - name: app_gitRepo
    type: GitRepo
    configuration:
      path: avishayh/mydemo
      gitProvider: mydemogit
  - name:       firstOutputResource
    type:       FileSpec
    configuration:     
      sourceArtifactory:    artifactoryIntegration
      # pattern:               # required, either this or aql
      pattern: "example-repo-local/*.txt"
      # aql:                  <string>   # required, either this or pattern
      # target:                  # required to upload files
      # props:                <string>   # optional
      # recursive:            <boolean>  # optional
      # flat:                 <boolean>  # optional
      # excludePatterns:      <string>   # optional
      # archiveEntries:       <string>   # optional
      # buildName:            <string>   # optional
      # buildNumber:          <integer>  # optional
      # sortBy:               <string>   # optional
      # sortOrder:            <string>   # optional
      # limit:                <integer>  # optional
      # offset:               <integer>  # optional
  - name: my_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: undefined
      buildNumber: -1

pipelines:
  - name: my_first_pipeline
    steps:
      - name: p1_s1
        type: Bash
        configuration:
          inputResources:
            - name: app_gitRepo 
          outputResources:
            - name: my_build_info    
        execution:
          onExecute:
            # Data from input resources is available as env variables in the step
            - echo $res_myFirstRepo_commitSha
            # The next two commands add variables to run state, which is available to all downstream steps in this run
            # Run state documentation: https://www.jfrog.com/confluence/display/JFROG/Creating+Stateful+Pipelines#CreatingStatefulPipelines-RunState
            - add_run_variables current_runid=$run_id
            - add_run_variables commitSha=$res_myFirstRepo_commitSha
            # This variable is written to pipeline state in p1_s3.
            # So this will be empty during first run and will be set to prior run number in subsequent runs
            # Pipeline state documentation: https://www.jfrog.com/confluence/display/JFROG/Creating+Stateful+Pipelines#CreatingStatefulPipelines-PipelineState
            - echo "Previous run ID is $prev_runid"
 
    